/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Baker;
import service.BakerService;

/**
 *
 * @author Noella
 */
public class BakerForm extends javax.swing.JFrame {

    /**
     * Creates new form BakerForm
     */
    public BakerForm() {
        initComponents();
        
    }
    
    private void clearFields(){
    bakeridtxt.setText("");
    fullnametxt.setText("");
    phonetxt.setText("");
    specializationtxt.setText("");
}
    private void displayBakers(){

    try{
        Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);

        BakerService service =
        (BakerService) reg.lookup("baker");

        List<Baker> bakers = service.findAllBakers();

        DefaultTableModel model =
        (DefaultTableModel) bakerTable.getModel();

        model.setRowCount(0);

        for(Baker baker : bakers){

            Object row[] = {
                baker.getBakerId(),
                baker.getFullName(),
                baker.getPhone(),
                baker.getSpecialization()
            };

            model.addRow(row);
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Table Error: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bakerTable = new javax.swing.JTable();
        jTable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bakeridtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fullnametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        specializationtxt = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        viewallbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noella\\Documents\\NetBeansProjects\\SweetBiteBakeryMgtSystemClient26749\\images\\bakery.jpg.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        bakerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bakerTable);

        jTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable.setText("BAKER TABLE");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Baker ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Specialization");

        backbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        viewallbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        viewallbtn.setText("View All");
        viewallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallbtnActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        searchbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backbtn)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savebtn)
                                        .addGap(31, 31, 31)
                                        .addComponent(updatebtn))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(viewallbtn)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bakeridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(deletebtn)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(specializationtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                        .addComponent(phonetxt, javax.swing.GroupLayout.Alignment.LEADING)))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clearbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchbtn)
                                .addGap(80, 80, 80)))))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jTable)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTable)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backbtn)
                        .addGap(171, 171, 171)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bakeridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(specializationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebtn)
                            .addComponent(updatebtn)
                            .addComponent(deletebtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearbtn)
                            .addComponent(searchbtn))
                        .addGap(60, 60, 60)
                        .addComponent(viewallbtn)
                        .addGap(81, 81, 81)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
         try{

        if(bakeridtxt.getText().isEmpty()
                || fullnametxt.getText().isEmpty()
                || phonetxt.getText().isEmpty()
                || specializationtxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "Fill all fields");

        }else{
            
            //validations 
            
             if(!bakeridtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this, "Baker ID must be numbers only");
               
        return;
    }

    if(!fullnametxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this, "Full Name must contain letters only");
               
        return;
    }

    if(!phonetxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Phone must contain digits only");
                
        return;
    }

    if(phonetxt.getText().length() != 10){
        JOptionPane.showMessageDialog(this,"Phone must be 10 digits");
                
        return;
    }

    if(!specializationtxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this, "Specialization must contain letters only");
               
        return;
    }

            Baker baker = new Baker();

            baker.setBakerId(Integer.parseInt(bakeridtxt.getText()));
            baker.setFullName(fullnametxt.getText());
            baker.setPhone(phonetxt.getText());
            baker.setSpecialization(specializationtxt.getText());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            BakerService service = (BakerService) reg.lookup("baker");

            Baker saved = service.registerBaker(baker);

            if(saved != null){
                JOptionPane.showMessageDialog(this, "Baker Saved Successfully");
                displayBakers();
                clearFields();
            }else{
                JOptionPane.showMessageDialog(this, "Baker Not Saved");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_savebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
         try{

        if(bakeridtxt.getText().isEmpty()
                || fullnametxt.getText().isEmpty()
                || phonetxt.getText().isEmpty()
                || specializationtxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "Fill all fields");

        }else{
            
            //validations
            
             if(!bakeridtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this, "Baker ID must be numbers only");
               
        return;
    }

    if(!fullnametxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this, "Full Name must contain letters only");
               
        return;
    }

    if(!phonetxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Phone must contain digits only");
                
        return;
    }

    if(phonetxt.getText().length() != 10){
        JOptionPane.showMessageDialog(this,"Phone must be 10 digits");
                
        return;
    }

    if(!specializationtxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this, "Specialization must contain letters only");
               
        return;
    }

            Baker baker = new Baker();

            baker.setBakerId(Integer.parseInt(bakeridtxt.getText()));
            baker.setFullName(fullnametxt.getText());
            baker.setPhone(phonetxt.getText());
            baker.setSpecialization(specializationtxt.getText());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            BakerService service = (BakerService) reg.lookup("baker");

            Baker updated = service.updateBaker(baker);

            if(updated != null){
                JOptionPane.showMessageDialog(this, "Baker Updated Successfully");
                displayBakers();
                clearFields();
            }else{
                JOptionPane.showMessageDialog(this, "Baker Not Updated");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Update Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
         try{

        if(bakeridtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Baker ID");
        }else{

            int bakerId = Integer.parseInt(bakeridtxt.getText());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            BakerService service = (BakerService) reg.lookup("baker");

            Baker baker = service.searchBaker(bakerId);

            if(baker != null){
                Baker deleted = service.deleteBaker(baker);

                if(deleted != null){
                    JOptionPane.showMessageDialog(this, "Baker Deleted Successfully");
                    displayBakers();
                    clearFields();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Baker Not Found");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Delete Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
         try{

        if(bakeridtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Baker ID");
        }else{

            int bakerId = Integer.parseInt(bakeridtxt.getText());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            BakerService service = (BakerService) reg.lookup("baker");

            Baker baker = service.searchBaker(bakerId);

            if(baker != null){
                bakeridtxt.setText(String.valueOf(baker.getBakerId()));
                fullnametxt.setText(baker.getFullName());
                phonetxt.setText(baker.getPhone());
                specializationtxt.setText(baker.getSpecialization());
            }else{
                JOptionPane.showMessageDialog(this, "Baker Not Found");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Search Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
         clearFields();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void viewallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallbtnActionPerformed
        displayBakers();
    }//GEN-LAST:event_viewallbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
          DashboardForm dashboard = new DashboardForm();
    dashboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BakerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BakerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BakerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BakerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BakerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTable bakerTable;
    private javax.swing.JTextField bakeridtxt;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField fullnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTable;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField specializationtxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewallbtn;
    // End of variables declaration//GEN-END:variables
}
