/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cake;
import service.CakeService;

/**
 *
 * @author Noella
 */
public class CakeForm extends javax.swing.JFrame {

    /**
     * Creates new form CakeForm
     */
    public CakeForm() {
        initComponents();
        addTableHeader();
        displayCakes();
    }
     private void addTableHeader(){

    DefaultTableModel model = (DefaultTableModel) cakeTable.getModel();

    Object[] columns = {
        "Cake ID",
        "Cake Name",
        "Flavor",
        "Size",
        "Price"
    };

    model.setColumnIdentifiers(columns);
}

private void displayCakes(){

    try{
        Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);

        CakeService service =
        (CakeService) reg.lookup("cake");

        List<Cake> cakes = service.findAllCakes();

        DefaultTableModel model =
        (DefaultTableModel) cakeTable.getModel();

        model.setRowCount(0);

        for(Cake cake : cakes){

            Object row[] = {
                cake.getCakeId(),
                cake.getCakeName(),
                cake.getFlavor(),
                cake.getSize(),
                cake.getPrice()
            };

            model.addRow(row);
        }

    }catch(Exception ex){
        ex.printStackTrace();
    }
}

private void clearFields(){
    cakeidtxt.setText("");
    cakenametxt.setText("");
    flavortxt.setText("");
    sizetxt.setText("");
    pricetxt.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cakeidtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cakenametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        flavortxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sizetxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        viewallbtn = new javax.swing.JButton();
        backtodashboardbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cakeTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noella\\Documents\\NetBeansProjects\\SweetBiteBakeryMgtSystemClient26749\\images\\bakery.jpg.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cake ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cake Name");

        cakenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakenametxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Flavor");

        flavortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flavortxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Size");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");

        savebtn.setBackground(new java.awt.Color(255, 102, 255));
        savebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(204, 0, 204));
        updatebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(204, 0, 204));
        deletebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(204, 0, 204));
        searchbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(153, 0, 153));
        clearbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        viewallbtn.setBackground(new java.awt.Color(204, 0, 204));
        viewallbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        viewallbtn.setText("View All");
        viewallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallbtnActionPerformed(evt);
            }
        });

        backtodashboardbtn.setBackground(new java.awt.Color(204, 0, 204));
        backtodashboardbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backtodashboardbtn.setText("Back to Dashboard");
        backtodashboardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtodashboardbtnActionPerformed(evt);
            }
        });

        cakeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cakeTable);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CAKE TABLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cakeidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cakenametxt)
                                                .addComponent(flavortxt, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(pricetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(sizetxt, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savebtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(updatebtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deletebtn)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viewallbtn)
                                            .addComponent(searchbtn)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(clearbtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backtodashboardbtn)
                        .addGap(71, 71, 71)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backtodashboardbtn)
                        .addGap(162, 162, 162)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cakeidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cakenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(flavortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebtn)
                            .addComponent(updatebtn)
                            .addComponent(deletebtn)
                            .addComponent(searchbtn))
                        .addGap(46, 46, 46)
                        .addComponent(clearbtn)
                        .addGap(15, 15, 15)
                        .addComponent(viewallbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cakenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cakenametxtActionPerformed

    private void flavortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flavortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flavortxtActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clearFields();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
         try{

        if(cakeidtxt.getText().isEmpty()
                || cakenametxt.getText().isEmpty()
                || flavortxt.getText().isEmpty()
                || sizetxt.getText().isEmpty()
                || pricetxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "Fill all fields");

        }else{
            
            //validations
            
                if(!cakeidtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Cake ID must be numbers only");
                
        return;
    }

    if(!cakenametxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this,"Cake Name must contain letters only");
                
        return;
    }

    if(!flavortxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this,"Flavor must contain letters only");
                
        return;
    }

    if(!pricetxt.getText().matches("[0-9.]+")){
        JOptionPane.showMessageDialog(this,"Price must be numeric");
                
        return;
    }

    double price = Double.parseDouble(pricetxt.getText());

    if(price < 1000){
        JOptionPane.showMessageDialog(this,"Cake price must be at least 1000 RWF");
                
        return;
    }


            Cake cake = new Cake();

            cake.setCakeId(Integer.parseInt(cakeidtxt.getText()));
            cake.setCakeName(cakenametxt.getText());
            cake.setFlavor(flavortxt.getText());
            cake.setSize(sizetxt.getText());
            cake.setPrice(Double.parseDouble(pricetxt.getText()));

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);

            CakeService service =
            (CakeService) reg.lookup("cake");

            Cake saved = service.registerCake(cake);

            if(saved != null){
                JOptionPane.showMessageDialog(this, "Cake Saved Successfully");

                displayCakes();   // this makes JTable refresh
                clearFields();

            }else{
                JOptionPane.showMessageDialog(this, "Cake Not Saved");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    } 
    }//GEN-LAST:event_savebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
         try{

        if(cakeidtxt.getText().isEmpty()
                || cakenametxt.getText().isEmpty()
                || flavortxt.getText().isEmpty()
                || sizetxt.getText().isEmpty()
                || pricetxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "Fill all fields");

        }else{
            
            //validations
            
             if(!cakeidtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Cake ID must be numbers only");
                
        return;
    }

    if(!cakenametxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this,"Cake Name must contain letters only");
                
        return;
    }

    if(!flavortxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this,"Flavor must contain letters only");
                
        return;
    }

    if(!pricetxt.getText().matches("[0-9.]+")){
        JOptionPane.showMessageDialog(this,"Price must be numeric");
                
        return;
    }

    double price = Double.parseDouble(pricetxt.getText());

    if(price < 1000){
        JOptionPane.showMessageDialog(this,"Cake price must be at least 1000 RWF");
                
        return;
    }

            Cake cake = new Cake();

            cake.setCakeId(Integer.parseInt(cakeidtxt.getText()));
            cake.setCakeName(cakenametxt.getText());
            cake.setFlavor(flavortxt.getText());
            cake.setSize(sizetxt.getText());
            cake.setPrice(Double.parseDouble(pricetxt.getText()));

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            CakeService service = (CakeService) reg.lookup("cake");

            Cake updated = service.updateCake(cake);

            if(updated != null){
                JOptionPane.showMessageDialog(this, "Cake Updated Successfully");
                displayCakes();
                clearFields();
            }else{
                JOptionPane.showMessageDialog(this, "Cake Not Updated");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Update Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try{

        if(cakeidtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Cake ID");
        }else{

            int cakeId = Integer.parseInt(cakeidtxt.getText());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            CakeService service = (CakeService) reg.lookup("cake");

            Cake cake = service.searchCake(cakeId);

            if(cake != null){
                Cake deleted = service.deleteCake(cake);

                if(deleted != null){
                    JOptionPane.showMessageDialog(this, "Cake Deleted Successfully");
                    displayCakes();
                    clearFields();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Cake Not Found");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Delete Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
         try{

        if(cakeidtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Cake ID");
        }else{

            int cakeId = Integer.parseInt(cakeidtxt.getText());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5004);
            CakeService service = (CakeService) reg.lookup("cake");

            Cake cake = service.searchCake(cakeId);

            if(cake != null){

                cakeidtxt.setText(String.valueOf(cake.getCakeId()));
                cakenametxt.setText(cake.getCakeName());
                flavortxt.setText(cake.getFlavor());
                sizetxt.setText(cake.getSize());
                pricetxt.setText(String.valueOf(cake.getPrice()));

            }else{
                JOptionPane.showMessageDialog(this, "Cake Not Found");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Search Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void viewallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallbtnActionPerformed
        displayCakes();
    }//GEN-LAST:event_viewallbtnActionPerformed

    private void backtodashboardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtodashboardbtnActionPerformed
           DashboardForm dashboard = new DashboardForm();
    dashboard.setVisible(true);
    this.dispose();        
    }//GEN-LAST:event_backtodashboardbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CakeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtodashboardbtn;
    private javax.swing.JTable cakeTable;
    private javax.swing.JTextField cakeidtxt;
    private javax.swing.JTextField cakenametxt;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField flavortxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField sizetxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewallbtn;
    // End of variables declaration//GEN-END:variables
}
