/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import service.CustomerService;
import java.util.List;

/**
 *
 * @author Noella
 */
public class CustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        addTableHeader();
        displayCustomers();
       }
       
     private void addTableHeader(){

    DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
            

    Object[] columns = {
        "Customer ID",
        "Full Name",
        "Phone",
        "Email", 
        "Address"
    };

    model.setColumnIdentifiers(columns);
}
        
        private void displayCustomers(){
                 try{

        Registry reg =
        LocateRegistry.getRegistry("127.0.0.1",5004);

        CustomerService service =
        (CustomerService) reg.lookup("customer");

        List<Customer> customers =
        service.findAllCustomers();

        DefaultTableModel model =
        (DefaultTableModel) customerTable.getModel();

        model.setRowCount(0);

        for(Customer customer : customers){

            Object row[] = {

                customer.getCustomerId(),
                customer.getFullName(),
                customer.getPhone(),
                customer.getEmail(),
                customer.getAddress()
            };

            model.addRow(row);
        }

    }catch(Exception ex){

        ex.printStackTrace();
    }
        } 
        
        private void clearFields(){
            customeridtxt.setText("");
            fullnametxt.setText("");
            phonetxt.setText("");
            emailtxt.setText("");
            addresstxt.setText("");
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customeridtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fullnametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        viewallbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        customertable = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noella\\Documents\\NetBeansProjects\\SweetBiteBakeryMgtSystemClient26749\\images\\customer.jpg.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 1000));

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer ID");

        customeridtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridtxtActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Full Name");

        jLabel6.setBackground(new java.awt.Color(204, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setBackground(new java.awt.Color(204, 102, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");

        savebtn.setBackground(new java.awt.Color(153, 0, 0));
        savebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(153, 0, 0));
        updatebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(153, 0, 0));
        deletebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(153, 0, 0));
        searchbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(153, 0, 0));
        clearbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        backbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        viewallbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        viewallbtn.setText("View All");
        viewallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savebtn)
                                .addGap(18, 18, 18)
                                .addComponent(updatebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deletebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchbtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customeridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backbtn)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(clearbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewallbtn)
                        .addGap(80, 80, 80)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backbtn)
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(customeridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(updatebtn)
                    .addComponent(deletebtn)
                    .addComponent(searchbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearbtn)
                    .addComponent(viewallbtn))
                .addContainerGap())
        );

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Tittle 2", "Tiltle 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(customerTable);

        customertable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customertable.setText("CUSTOMER TABLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(customertable)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(customertable)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customeridtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridtxtActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try{

        if(customeridtxt.getText().isEmpty()
                || fullnametxt.getText().isEmpty()
                || phonetxt.getText().isEmpty()
                || emailtxt.getText().isEmpty()
                || addresstxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Fill all fields");

        }else{
               //validations
             if(!customeridtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this, "Customer ID must be numbers only");

                       return;
    }

    if(!fullnametxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this,"Full Name must contain letters only");
                
        return;
    }

    if(!phonetxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Phone must contain digits only");
                
        return;
    }

    if(phonetxt.getText().length() != 10){
        JOptionPane.showMessageDialog(this,"Phone must be 10 digits");
                
        return;
    }

    if(!emailtxt.getText().contains("@")){
        JOptionPane.showMessageDialog(this,"Invalid Email");
                
        return;
    }

            int customerId =
            Integer.parseInt(customeridtxt.getText());

            String fullname =
            fullnametxt.getText();

            String phone =
            phonetxt.getText();

            String email =
            emailtxt.getText();

            String address =
            addresstxt.getText();

            Registry reg =
            LocateRegistry.getRegistry("127.0.0.1",5004);

            CustomerService service =
            (CustomerService) reg.lookup("customer");

            Customer customer = new Customer();

            customer.setCustomerId(customerId);
            customer.setFullName(fullname);
            customer.setPhone(phone);
            customer.setEmail(email);
            customer.setAddress(address);

            Customer saved =
            service.registerCustomer(customer);

            if(saved != null){

                JOptionPane.showMessageDialog(this,
                        "Customer Saved Successfully");

                displayCustomers();
                clearFields();

            }else{

                JOptionPane.showMessageDialog(this,
                        "Failed");
            }
        }

    }catch(Exception ex){

        ex.printStackTrace();
    }
    }//GEN-LAST:event_savebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        
    customeridtxt.setText("");
    fullnametxt.setText("");
    phonetxt.setText("");
    emailtxt.setText("");
    addresstxt.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
             try{

        if(customeridtxt.getText().isEmpty()
                || fullnametxt.getText().isEmpty()
                || phonetxt.getText().isEmpty()
                || emailtxt.getText().isEmpty()
                || addresstxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Fill all fields");

        }else{
               //validations
                if(!customeridtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Customer ID must be numbers only");
                
        return;
    }

    if(!fullnametxt.getText().matches("[A-Za-z ]+")){
        JOptionPane.showMessageDialog(this, "Full Name must contain letters only");
               
        return;
    }

    if(!phonetxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Phone must contain digits only");
                
        return;
    }

    if(phonetxt.getText().length() != 10){
        JOptionPane.showMessageDialog(this,"Phone must be 10 digits");
                
        return;
    }

    if(!emailtxt.getText().contains("@")){
        JOptionPane.showMessageDialog(this,"Invalid Email");
                
        return;
    }
            

            int customerId =
            Integer.parseInt(customeridtxt.getText());

            String fullname =
            fullnametxt.getText();

            String phone =
            phonetxt.getText();

            String email =
            emailtxt.getText();

            String address =
            addresstxt.getText();

            Registry reg =
            LocateRegistry.getRegistry("127.0.0.1",5004);

            CustomerService service =
            (CustomerService) reg.lookup("customer");

            Customer customer = new Customer();

            customer.setCustomerId(customerId);
            customer.setFullName(fullname);
            customer.setPhone(phone);
            customer.setEmail(email);
            customer.setAddress(address);

            Customer updated =
            service.updateCustomer(customer);

            if(updated != null){

                JOptionPane.showMessageDialog(this,
                        "Customer Updated");

                displayCustomers();
                clearFields();

            }else{

                JOptionPane.showMessageDialog(this,
                        "Update Failed");
            }
        }

    }catch(Exception ex){

        ex.printStackTrace();
    }

    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try{

        if(customeridtxt.getText().isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Enter Customer ID");

        }else{

            int customerId =
            Integer.parseInt(customeridtxt.getText());

            Registry reg =
            LocateRegistry.getRegistry("127.0.0.1",5004);

            CustomerService service =
            (CustomerService) reg.lookup("customer");

            Customer customer = new Customer();

            customer.setCustomerId(customerId);

            Customer deleted =
            service.deleteCustomer(customer);

            if(deleted != null){

                JOptionPane.showMessageDialog(this,
                        "Customer Deleted");

                displayCustomers();
                clearFields();

            }else{

                JOptionPane.showMessageDialog(this,
                        "Delete Failed");
            }
        }

    }catch(Exception ex){

        ex.printStackTrace();
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
         try{

        int customerId =
        Integer.parseInt(customeridtxt.getText());

        Registry reg =
        LocateRegistry.getRegistry("127.0.0.1",5004);

        CustomerService service =
        (CustomerService) reg.lookup("customer");

        Customer customer =
        service.searchCustomer(customerId);

        if(customer != null){

            customeridtxt.setText(
            String.valueOf(customer.getCustomerId()));

            fullnametxt.setText(
            customer.getFullName());

            phonetxt.setText(
            customer.getPhone());

            emailtxt.setText(
            customer.getEmail());

            addresstxt.setText(
            customer.getAddress());

        }else{

            JOptionPane.showMessageDialog(this,
            "Customer Not Found");
        }

    }catch(Exception ex){

        ex.printStackTrace();
    }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void viewallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallbtnActionPerformed
        displayCustomers();
    }//GEN-LAST:event_viewallbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        DashboardForm dashboard = new DashboardForm();
    dashboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField customeridtxt;
    private javax.swing.JLabel customertable;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fullnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewallbtn;
    // End of variables declaration//GEN-END:variables
}
