/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CakeOrder;
import model.Payment;
import service.CakeOrderService;
import service.PaymentService;

/**
 *
 * @author Noella
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
         setTableColumns();
         loadOrders();
         loadPaymentMethods();
    }
    
    private void clearFields(){

    paymentidtxt.setText("");
    amounttxt.setText("");

    ordercmb.setSelectedIndex(0);
    paymentmethodcmb.setSelectedIndex(0);

    paymentdatechooser.setDate(null);
}
    
    
    private void displayPayments(){

    try{
        Registry reg =
                LocateRegistry.getRegistry("127.0.0.1",5004);

        PaymentService service =
                (PaymentService) reg.lookup("payment");

        List<Payment> payments =
                service.findAllPayments();

        DefaultTableModel model =
                (DefaultTableModel) paymentTable.getModel();

        model.setRowCount(0);

        for(Payment payment : payments){

            Object row[] = {
                payment.getPaymentId(),
                payment.getOrder().getOrderId(),
                payment.getAmount(),
                payment.getPaymentMethod(),
                payment.getPaymentDate()
            };

            model.addRow(row);
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Table Error: " + ex.getMessage());
    }
}
    
    
    private void loadPaymentMethods(){

    paymentmethodcmb.removeAllItems();

    paymentmethodcmb.addItem("Cash");
    paymentmethodcmb.addItem("Mobile Money");
    paymentmethodcmb.addItem("Bank Transfer");
    paymentmethodcmb.addItem("Card");
}
    
    private void setTableColumns(){

    DefaultTableModel model = (DefaultTableModel) paymentTable.getModel();
            

    model.setColumnIdentifiers(new Object[]{
        "Payment ID",
        "Order ID",
        "Amount",
        "Payment Method",
        "Payment Date"
    });

    model.setRowCount(0);
}
    
    private void loadOrders(){

    try{

        Registry reg = LocateRegistry.getRegistry("127.0.0.1",5004);
                

        CakeOrderService service = (CakeOrderService) reg.lookup("order");
                

        List<CakeOrder> orders = service.findAllOrders();
               

        ordercmb.removeAllItems();

        for(CakeOrder order : orders){

            ordercmb.addItem(String.valueOf(order.getOrderId()));
                    
        }

    }catch(Exception ex){

        ex.printStackTrace();

        JOptionPane.showMessageDialog(this,
                "Order Loading Error");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paymentidtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amounttxt = new javax.swing.JTextField();
        paymentmethodcmb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        viewallbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        paymentdatechooser = new com.toedter.calendar.JDateChooser();
        ordercmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noella\\Documents\\NetBeansProjects\\SweetBiteBakeryMgtSystemClient26749\\images\\user.jpg.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Payment ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Order");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Payment Method");

        paymentmethodcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Payment Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PAYMENT TABLE");

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(paymentTable);

        savebtn.setBackground(new java.awt.Color(204, 204, 0));
        savebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(153, 153, 0));
        updatebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(153, 153, 0));
        deletebtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(153, 153, 0));
        searchbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        viewallbtn.setBackground(new java.awt.Color(153, 153, 0));
        viewallbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        viewallbtn.setText("View All");
        viewallbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallbtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(153, 153, 0));
        clearbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(153, 153, 0));
        backbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        ordercmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(888, 888, 888)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(paymentidtxt)
                                            .addComponent(amounttxt)
                                            .addComponent(ordercmb, 0, 147, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(paymentmethodcmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(paymentdatechooser, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clearbtn)
                                        .addGap(50, 50, 50)
                                        .addComponent(viewallbtn)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savebtn)
                                        .addGap(26, 26, 26)
                                        .addComponent(updatebtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(deletebtn)))))
                        .addGap(300, 300, 300)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(backbtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(searchbtn))
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(paymentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ordercmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(paymentmethodcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(paymentdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(updatebtn)
                    .addComponent(deletebtn))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewallbtn)
                    .addComponent(clearbtn))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try{

        if(paymentidtxt.getText().isEmpty()
                || amounttxt.getText().isEmpty()
                || ordercmb.getSelectedItem() == null
                || paymentdatechooser.getDate() == null){

            JOptionPane.showMessageDialog(this,
                    "Fill all fields");

        }else{
            
            //validations
            
            if(!paymentidtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Payment ID must be numbers only");
                
        return;
    }

    if(!amounttxt.getText().matches("[0-9.]+")){
        JOptionPane.showMessageDialog(this, "Amount must be numeric");
               
        return;
    }

    double amount =
            Double.parseDouble(amounttxt.getText());

    if(amount <= 0){
        JOptionPane.showMessageDialog(this, "Amount must be greater than zero");
               
        return;
    }

            int orderId = Integer.parseInt(ordercmb.getSelectedItem().toString());
                   

            Registry reg =
                    LocateRegistry.getRegistry("127.0.0.1",5004);

            CakeOrderService orderService = (CakeOrderService) reg.lookup("order");
                   

            PaymentService paymentService = (PaymentService) reg.lookup("payment");
                    

            CakeOrder order =orderService.searchOrder(orderId);
                    

            Payment payment = new Payment();

            payment.setPaymentId( Integer.parseInt(paymentidtxt.getText()));
                   

            payment.setAmount(Double.parseDouble(amounttxt.getText()));
                    

            payment.setPaymentMethod( paymentmethodcmb.getSelectedItem().toString());
                   

            java.sql.Date paymentDate =
                    new java.sql.Date( paymentdatechooser.getDate().getTime());

                           
            payment.setPaymentDate(paymentDate);

            payment.setOrder(order);

            Payment saved = paymentService.registerPayment(payment);
                    

            if(saved != null){

                JOptionPane.showMessageDialog(this,
                        "Payment Saved Successfully");

                clearFields();

            }else{

                JOptionPane.showMessageDialog(this,
                        "Payment Not Saved");
            }
        }

    }catch(Exception ex){

        ex.printStackTrace();

        JOptionPane.showMessageDialog(this,
                "Save Error : " + ex.getMessage());
    }
    }//GEN-LAST:event_savebtnActionPerformed

    private void viewallbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallbtnActionPerformed
         displayPayments();
    }//GEN-LAST:event_viewallbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
         clearFields();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
         try{

        int paymentId =
                Integer.parseInt(paymentidtxt.getText());

        Registry reg =
                LocateRegistry.getRegistry("127.0.0.1",5004);

        PaymentService service =
                (PaymentService) reg.lookup("payment");

        Payment payment =
                service.searchPayment(paymentId);

        if(payment != null){

            paymentidtxt.setText(
                    String.valueOf(payment.getPaymentId()));

            ordercmb.setSelectedItem(
                    String.valueOf(payment.getOrder().getOrderId()));

            amounttxt.setText(
                    String.valueOf(payment.getAmount()));

            paymentmethodcmb.setSelectedItem(
                    payment.getPaymentMethod());

            paymentdatechooser.setDate(
                    payment.getPaymentDate());

        }else{
            JOptionPane.showMessageDialog(this,
                    "Payment Not Found");
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Search Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
         DashboardForm dashboard = new DashboardForm();
    dashboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try{

        if(paymentidtxt.getText().isEmpty()
                || amounttxt.getText().isEmpty()
                || ordercmb.getSelectedItem() == null
                || paymentdatechooser.getDate() == null){

            JOptionPane.showMessageDialog(this,
                    "Fill all fields");

        }else{
            
            //validations
            
             if(!paymentidtxt.getText().matches("[0-9]+")){
        JOptionPane.showMessageDialog(this,"Payment ID must be numbers only");
                
        return;
    }

    if(!amounttxt.getText().matches("[0-9.]+")){
        JOptionPane.showMessageDialog(this, "Amount must be numeric");
               
        return;
    }

    double amount =
            Double.parseDouble(amounttxt.getText());

    if(amount <= 0){
        JOptionPane.showMessageDialog(this, "Amount must be greater than zero");
               
        return;
    }

            int orderId = Integer.parseInt(ordercmb.getSelectedItem().toString());
                    

            Registry reg = LocateRegistry.getRegistry("127.0.0.1",5004);
                    

            CakeOrderService orderService =
                    (CakeOrderService) reg.lookup("order");

            PaymentService paymentService =
                    (PaymentService) reg.lookup("payment");

            CakeOrder order =
                    orderService.searchOrder(orderId);

            Payment payment = new Payment();

            payment.setPaymentId(
                    Integer.parseInt(paymentidtxt.getText()));

            payment.setAmount(
                    Double.parseDouble(amounttxt.getText()));

            payment.setPaymentMethod(
                    paymentmethodcmb.getSelectedItem().toString());

            java.sql.Date paymentDate =
                    new java.sql.Date(
                            paymentdatechooser.getDate().getTime());

            payment.setPaymentDate(paymentDate);
            payment.setOrder(order);

            Payment updated =
                    paymentService.updatePayment(payment);

            if(updated != null){
                JOptionPane.showMessageDialog(this,
                        "Payment Updated Successfully");
                displayPayments();
                clearFields();
            }else{
                JOptionPane.showMessageDialog(this,
                        "Payment Not Updated");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Update Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try{

        if(paymentidtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Enter Payment ID");
        }else{
            
           

            int paymentId = Integer.parseInt(paymentidtxt.getText());
                    

            Registry reg = LocateRegistry.getRegistry("127.0.0.1",5004);
                    

            PaymentService service =(PaymentService) reg.lookup("payment");
                    

            Payment payment = service.searchPayment(paymentId);

                   
            if(payment != null){

                Payment deleted = service.deletePayment(payment);
                        

                if(deleted != null){
                    JOptionPane.showMessageDialog(this,

                            "Payment Deleted Successfully");
                    displayPayments();
                    clearFields();
                }

            }else{
                JOptionPane.showMessageDialog(this,
                        "Payment Not Found");
            }
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Delete Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amounttxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ordercmb;
    private javax.swing.JTable paymentTable;
    private com.toedter.calendar.JDateChooser paymentdatechooser;
    private javax.swing.JTextField paymentidtxt;
    private javax.swing.JComboBox<String> paymentmethodcmb;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewallbtn;
    // End of variables declaration//GEN-END:variables
}
