/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileWriter;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CakeOrder;
import model.Payment;
import service.CakeOrderService;
import service.PaymentService;

/**
 *
 * @author Noella
 */
public class ReportForm extends javax.swing.JFrame {

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ordersreportbtn = new javax.swing.JButton();
        paymentsreportbtn = new javax.swing.JButton();
        exportcsvbtn = new javax.swing.JButton();
        printbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Noella\\Documents\\NetBeansProjects\\SweetBiteBakeryMgtSystemClient26749\\images\\report.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("REPORT FORM");

        ordersreportbtn.setBackground(new java.awt.Color(153, 153, 153));
        ordersreportbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ordersreportbtn.setText("Orders Report");
        ordersreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersreportbtnActionPerformed(evt);
            }
        });

        paymentsreportbtn.setBackground(new java.awt.Color(153, 153, 153));
        paymentsreportbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        paymentsreportbtn.setText("Payments Report");
        paymentsreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsreportbtnActionPerformed(evt);
            }
        });

        exportcsvbtn.setBackground(new java.awt.Color(153, 153, 153));
        exportcsvbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        exportcsvbtn.setText("Export CSV");
        exportcsvbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportcsvbtnActionPerformed(evt);
            }
        });

        printbtn.setBackground(new java.awt.Color(153, 153, 153));
        printbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(153, 153, 153));
        backbtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("REPORT TABLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentsreportbtn)
                                    .addComponent(ordersreportbtn)
                                    .addComponent(exportcsvbtn))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printbtn)
                        .addGap(73, 73, 73)
                        .addComponent(backbtn)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel3)
                        .addContainerGap(374, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(exportcsvbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printbtn)
                            .addComponent(backbtn))
                        .addGap(79, 79, 79)
                        .addComponent(ordersreportbtn)
                        .addGap(62, 62, 62)
                        .addComponent(paymentsreportbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
         try{
        boolean printed =
                reportTable.print();

        if(printed){
            JOptionPane.showMessageDialog(this,
                    "Report Printed Successfully");
        }else{
            JOptionPane.showMessageDialog(this,
                    "Printing Cancelled");
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Print Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_printbtnActionPerformed

    private void ordersreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersreportbtnActionPerformed
         try{
        Registry reg = LocateRegistry.getRegistry("127.0.0.1",5004);

        CakeOrderService service =(CakeOrderService) reg.lookup("order");
                

        List<CakeOrder> orders = service.findAllOrders();
               

        DefaultTableModel model =(DefaultTableModel) reportTable.getModel();
                

        model.setColumnIdentifiers(new Object[]{
            "Order ID",
            "Customer",
            "Quantity",
            "Total Amount",
            "Order Date",
            "Delivery Date",
            "Status"
        });

        model.setRowCount(0);

        for(CakeOrder order : orders){

            Object row[] = {
                order.getOrderId(),
                order.getCustomer().getFullName(),
                order.getQuantity(),
                order.getTotalAmount(),
                order.getOrderDate(),
                order.getDeliveryDate(),
                order.getStatus()
            };

            model.addRow(row);
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Orders Report Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_ordersreportbtnActionPerformed

    private void paymentsreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsreportbtnActionPerformed
         try{
        Registry reg = LocateRegistry.getRegistry("127.0.0.1",5004);

        PaymentService service =(PaymentService) reg.lookup("payment");

                
        List<Payment> payments = service.findAllPayments();
               

        DefaultTableModel model =(DefaultTableModel) reportTable.getModel();
                

        model.setColumnIdentifiers(new Object[]{
            "Payment ID",
            "Order ID",
            "Amount",
            "Payment Method",
            "Payment Date"
        });

        model.setRowCount(0);

        for(Payment payment : payments){

            Object row[] = {
                payment.getPaymentId(),
                payment.getOrder().getOrderId(),
                payment.getAmount(),
                payment.getPaymentMethod(),
                payment.getPaymentDate()
            };

            model.addRow(row);
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Payments Report Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_paymentsreportbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        DashboardForm dashboard = new DashboardForm();
    dashboard.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_backbtnActionPerformed

    private void exportcsvbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportcsvbtnActionPerformed
        try{
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Save CSV Report");

        int result = chooser.showSaveDialog(this);

        if(result == JFileChooser.APPROVE_OPTION){

            String path = chooser.getSelectedFile().getAbsolutePath();

            if(!path.endsWith(".csv")){
                path = path + ".csv";
            }

            FileWriter writer = new FileWriter(path);

            DefaultTableModel model =
                    (DefaultTableModel) reportTable.getModel();

            for(int i = 0; i < model.getColumnCount(); i++){
                writer.write(model.getColumnName(i) + ",");
            }

            writer.write("\n");

            for(int row = 0; row < model.getRowCount(); row++){

                for(int col = 0; col < model.getColumnCount(); col++){
                    writer.write(model.getValueAt(row, col).toString() + ",");
                }

                writer.write("\n");
            }

            writer.close();

            JOptionPane.showMessageDialog(this,
                    "CSV Report Exported Successfully");
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Export Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_exportcsvbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton exportcsvbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ordersreportbtn;
    private javax.swing.JButton paymentsreportbtn;
    private javax.swing.JButton printbtn;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables
}
